# Generated by Django 4.0.5 on 2022-06-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=30, verbose_name='Nombre')),
                ('area', models.CharField(choices=[('A-DW', 'Desarrollo Web'), ('A-RC', 'Redes y Comunicacion'), ('A-AS', 'Analista Sistemas')], max_length=5, verbose_name='Area')),
                ('fecha', models.DateField(verbose_name='Fecha Creacion')),
            ],
            options={
                'verbose_name_plural': 'departamento',
                'db_table': 'departamento',
            },
        ),
    ]
