# Generated by Django 4.0.5 on 2022-06-03 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Habilidad')),
            ],
            options={
                'verbose_name_plural': 'Habilidad',
                'db_table': 'habilidad',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=30, verbose_name='Apellidos')),
                ('puesto', models.CharField(max_length=30, verbose_name='Puesto')),
                ('image', models.ImageField(upload_to='empleado/img', verbose_name='Imagen')),
                ('fecha', models.DateField(verbose_name='Fecha Registro')),
                ('codigo_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamento.departamento', verbose_name='Departamento')),
                ('habilidad', models.ManyToManyField(to='empleado.habilidad', verbose_name='Habilidad')),
            ],
            options={
                'verbose_name_plural': 'Empleado',
                'db_table': 'empleado',
            },
        ),
    ]
